export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// EVENT TYPES
export const EVENT_LOADING = 'EVENT_LOADING';
export const LOADING_EDIT_EVENT = 'LOADING_EDIT_EVENT';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SEARCH_EVENT = 'SEARCH_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const UNARCHIVE_EVENT = 'UNARCHIVE_EVENT';
export const ARCHIVE_EVENT = 'ARCHIVE_EVENT';
export const IS_MODIFIED_EVENT = 'IS_MODIFIED_EVENT';

// PRESS TYPES
export const PRESS_LOADING = 'PRESS_LOADING';
export const GET_ALL_PRESS = 'GET_ALL_PRESS';
export const GET_PRESS = 'GET_PRESS';
export const ADD_PRESS = 'ADD_PRESS';
export const DELETE_PRESS = 'DELETE_PRESS';
export const SEARCH_PRESS = 'SEARCH_PRESS';
export const EDIT_PRESS = 'EDIT_PRESS';
export const GET_ARCHIVED = 'GET_ARCHIVED';
export const ARCHIVE_PRESS = 'ARCHIVE_PRESS';
export const UNARCHIVE_PRESS = 'UNARCHIVE_PRESS';
export const IS_MODIFIED_PRESS = 'IS_MODIFIED_PRESS';

// CLUB TYPES
export const CLUB_LOADING = 'CLUB_LOADING';
export const GET_CLUB = 'GET_CLUB';
export const GET_ALL_CLUB = 'GET_ALL_CLUB';
export const ADD_CLUB = 'ADD_CLUB';
export const DELETE_CLUB = 'DELETE_CLUB';
export const SEARCH_CLUB = 'SEARCH_CLUB';
export const EDIT_CLUB = 'EDIT_CLUB';
export const IS_MODIFIED_CLUB = 'IS_MODIFIED_CLUB';

// SLIDER TYPES
export const SLIDER_LOADING = 'SLIDER_LOADING';
export const GET_SLIDER = 'GET_SLIDER';
export const GET_ALL_SLIDER = 'GET_ALL_SLIDER';
export const ADD_SLIDER = 'ADD_SLIDER';
export const DELETE_SLIDER = 'DELETE_SLIDER';
export const SEARCH_SLIDER = 'SEARCH_SLIDER';
export const EDIT_SLIDER = 'EDIT_SLIDER';
export const GET_INACTIVE_SLIDER = 'GET_INACTIVE_SLIDER';
export const ARCHIVE_SLIDER = 'ARCHIVE_SLIDER';
export const UNARCHIVE_SLIDER = 'UNARCHIVE_SLIDER';
export const IS_MODIFIED_SLIDER = 'IS_MODIFIED_SLIDER';

// PARTNERSHIP TYPES
export const PARTNERSHIP_LOADING = 'PARTNERSHIP_LOADING';
export const GET_PARTNERSHIP = 'GET_PARTNERSHIP';
export const GET_ALL_PARTNERSHIP = 'GET_ALL_PARTNERSHIP';
export const ADD_PARTNERSHIP = 'ADD_PARTNERSHIP';
export const DELETE_PARTNERSHIP = 'DELETE_PARTNERSHIP';
export const SEARCH_PARTNERSHIP = 'SEARCH_PARTNERSHIP';
export const EDIT_PARTNERSHIP = 'EDIT_PARTNERSHIP';
export const IS_MODIFIED_PARTNERSHIP = 'IS_MODIFIED_PARTNERSHIP';

// RDI TYPES
export const RDI_LOADING = 'RDI_LOADING';
export const GET_RDI = 'GET_RDI';
export const GET_ALL_RDI = 'GET_ALL_RDI';
export const ADD_RDI = 'ADD_RDI';
export const DELETE_RDI = 'DELETE_RDI';
export const SEARCH_RDI = 'SEARCH_RDI';
export const EDIT_RDI = 'EDIT_RDI';
export const IS_MODIFIED_RDI = 'IS_MODIFIED_RDI';

// NEWS TYPES
export const NEWS_LOADING = 'NEWS_LOADING';
export const GET_NEWS = 'GET_NEWS';
export const GET_SINGLE_NEWS = 'GET_SINGLE_NEWS';
export const ADD_SINGLE_NEWS = 'ADD_SINGLE_NEWS';
export const DELETE_SINGLE_NEWS = 'DELETE_SINGLE_NEWS';
export const SEARCH_NEWS = 'SEARCH_NEWS';
export const EDIT_SINGLE_NEWS = 'EDIT_SINGLE_NEWS';
export const LOADING_EDIT_SINGLE_NEWS = 'LOADING_EDIT_SINGLE_NEWS';
export const UNARCHIVE_SINGLE_NEWS = 'UNARCHIVE_SINGLE_NEWS';
export const ARCHIVE_SINGLE_NEWS = 'ARCHIVE_SINGLE_NEWS';
export const IS_MODIFIED_SINGLE_NEWS = 'IS_MODIFIED_SINGLE_NEWS';

// DEPARTEMENT TYPES
export const DEPARTEMENT_LOADING = 'DEPARTEMENT_LOADING';
export const GET_ALL_DEPARTEMENT = 'GET_ALL_DEPARTEMENT';
export const GET_DEPARTEMENT = 'GET_DEPARTEMENT';
export const ADD_DEPARTEMENT = 'ADD_DEPARTEMENT';
export const DELETE_DEPARTEMENT = 'DELETE_DEPARTEMENT';
export const SEARCH_DEPARTEMENT = 'SEARCH_DEPARTEMENT';
export const EDIT_DEPARTEMENT = 'EDIT_DEPARTEMENT';

// CALENDAR TYPES
export const CALENDAR_LOADING = 'CALENDAR_LOADING';
export const GET_CALENDAR = 'GET_CALENDAR';
export const ADD_CALENDAR = 'ADD_CALENDAR';
export const EDIT_CALENDAR = 'EDIT_CALENDAR';
export const IS_MODIFIED_CALENDAR = 'IS_MODIFIED_CALENDAR';